[package]
name = "wm-generated"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[build-dependencies]
fancy-regex = { workspace = true }
serde_json = { workspace = true }

[lints]
workspace = true
