# Reference: https://docs.docker.com/reference/compose-file/
name: windows-monitor

services:
  elasticsearch:
    build:
      dockerfile: elastic-stack.Dockerfile
      target: elasticsearch
    container_name: elasticsearch
    cpus: 2.0
    hostname: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    restart: unless-stopped

  kibana:
    build:
      dockerfile: elastic-stack.Dockerfile
      target: kibana
    container_name: kibana
    cpus: 2.0
    depends_on:
      - elasticsearch
    hostname: kibana
    ports:
      - 5601:5601
    restart: unless-stopped
