cluster.name: "docker-cluster"
network.host: 0.0.0.0

discovery.type: "single-node"
xpack.security.enabled: true
# xpack.security.enrollment.enabled: false
# xpack.security.http.ssl.enabled: true
# xpack.security.http.ssl.keystore.path: "http.p12"
