name: Benchmark

on: [ push, pull_request ]

env:
  WINDOWS_MONITOR_PASSWORD: password

permissions:
  contents: read

jobs:
  benchmark:
    name: Benchmark resource usage
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: 1.89
          cache: false

      - name: Check processor information
        run: Get-CimInstance Win32_Processor | Format-List *

      - name: Setup workspace
        run: scripts\setup.bat

      - name: Setup RabbitMQ
        shell: cmd
        run: |
          mkdir rabbitmq
          set RABBITMQ_BASE=%cd%\rabbitmq
          choco install rabbitmq --version 4.1.4
          sc query RabbitMQ

      - name: Build workspace
        run: cargo build --release

      - name: Setup data collector
        run: scripts\data-collector.bat create

      - name: Start data collector
        run: scripts\data-collector.bat start

      - name: Start system and benchmark
        shell: cmd
        run: |
          target\release\utility use-default-password "SOFTWARE\WindowsMonitor\CertificatePassword"
          start target\release\wm-data-service.exe start
          start target\release\wm-api-service.exe start
          start target\release\wm-client.exe start
          tasklist
          waitfor SomethingThatIsNeverHappening /t 600 2>nul || type nul>nul

      - name: Stop data collector
        run: scripts\data-collector.bat stop

      - name: Upload benchmark results
        uses: actions/upload-artifact@v4
        with:
          name: benchmark
          path: |
            rabbitmq\log
            target\benchmark*
            target\release\logs
