name: Benchmark

on: [ push, pull_request ]

env:
  WINDOWS_MONITOR_PASSWORD: password

permissions:
  contents: read

jobs:
  benchmark:
    name: Benchmark resource usage
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        profile: [debug, release]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: 1.89
          cache: false
          rustflags: ""

      - name: Check processor information
        run: Get-CimInstance Win32_Processor | Format-List *

      - name: Setup workspace
        run: scripts\setup.bat

      - name: Setup RabbitMQ
        shell: cmd
        run: |
          mkdir rabbitmq
          set RABBITMQ_BASE=%cd%\rabbitmq
          choco install rabbitmq --version 4.1.4
          sc query RabbitMQ

      - name: Build workspace
        shell: cmd
        run: |
          if "${{ matrix.profile }}" == "debug" (
            cargo build
          ) else (
            cargo build --${{ matrix.profile }}
          )

      - name: Setup data collector
        run: scripts\data-collector.bat create

      - name: Start data collector
        run: scripts\data-collector.bat start

      - name: Start system and benchmark
        shell: cmd
        run: |
          target\${{ matrix.profile }}\utility use-default-password "SOFTWARE\WindowsMonitor\CertificatePassword"
          start target\${{ matrix.profile }}\wm-data-service.exe start
          start target\${{ matrix.profile }}\wm-api-service.exe start
          start target\${{ matrix.profile }}\wm-client.exe start
          tasklist
          waitfor SomethingThatIsNeverHappening /t 600 2>nul || type nul>nul

      - name: Stop data collector
        run: scripts\data-collector.bat stop

      - name: Upload benchmark results
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-${{ matrix.profile }}
          path: |
            rabbitmq\log
            target\benchmark*
            target\${{ matrix.profile }}\logs
