name: Build

on: [ push, pull_request ]

env:
  WINDOWS_MONITOR_PASSWORD: password

permissions:
  contents: read

jobs:
  build:
    name: Test build
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        target: [aarch64-pc-windows-msvc, i686-pc-windows-msvc, x86_64-pc-windows-gnu, x86_64-pc-windows-msvc]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: 1.89
          target: ${{ matrix.target }}
          cache: false

      - name: Setup workspace
        run: scripts\setup.bat

      - name: Build utility
        run: cargo build --release -p utility --target ${{ matrix.target }}

      - name: Build wm-api-service
        run: cargo build --release -p wm-api-service --target ${{ matrix.target }}

      - name: Build wm-client
        run: cargo build --release -p wm-client --target ${{ matrix.target }}

      - name: Build wm-common
        run: cargo build --release -p wm-common --target ${{ matrix.target }}

      - name: Build wm-data-service
        run: cargo build --release -p wm-data-service --target ${{ matrix.target }}

      - name: Build wm-generated
        run: cargo build --release -p wm-generated --target ${{ matrix.target }}

      - name: Package executables
        shell: cmd
        run: |
          mkdir packages packages\cert packages\utility packages\wm-api-service packages\wm-client packages\wm-data-service
          xcopy cert packages\cert\

          copy target\${{ matrix.target }}\release\utility.exe packages\utility\

          copy target\${{ matrix.target }}\release\wm-api-service.exe packages\wm-api-service\
          copy target\release\api-service-config.yml packages\wm-api-service\

          copy target\${{ matrix.target }}\release\wm-client.exe packages\wm-client\
          copy target\release\client-config.yml packages\wm-client\

          copy target\${{ matrix.target }}\release\wm-data-service.exe packages\wm-data-service\
          copy target\release\data-service-config.yml packages\wm-data-service\

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.target }}
          path: packages
