name: Lint

on: [ push, pull_request ]

env:
  WINDOWS_MONITOR_PASSWORD: password

permissions:
  contents: read

jobs:
  rustfmt:
    name: Run rustfmt
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly,1.89
          components: clippy,rustfmt

      - name: Setup workspace
        run: scripts\setup.bat

      - name: Run rustfmt via cargo fmt
        run: cargo +nightly fmt -- --check

  clippy:
    name: Run clippy
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly,1.89
          components: clippy,rustfmt

      - name: Setup workspace
        run: scripts\setup.bat

      - name: Run clippy
        run: cargo clippy --all-features --no-deps -- -D warnings
